base:
  project: complaint-project
  random_state: 0
  target_col: TARGET

data_source:
  s3_source: data_given/com.csv

load_data:
  raw_dataset_csv: data/raw/com.csv

split_data:
  train_path: data/processed/train_com.csv
  test_path: data/processed/test_com.csv
  test_size: 0.1

estimators:
  ElasticNet:
    params:
      
model_dir: saved_models